### PR TITLE
Test for "new Boolean(false)"

### PR DESCRIPTION
**Pull request by ROMB**
This is must not be false, as result of new Boolean(false) is object.

### CODE REVIEW

**Comment by btd** [comment]
should.js unwrap all primitive type wrappers to their actual values. it is by design true.

**Comment by ROMB** [comment]
But should thinks it's false. Try the test.

**Comment by btd** [comment]
I know the test will fail. But test from should.js perspective is wrong.

From logical point of view, why you think we should not extract from Boolean its value?

**Comment by ROMB** [comment]
because if(new Boolean(false)) will be true.

**Comment by ROMB** [comment]
This is mistake that some one can make in javascript code
if(Boolean(false)) - false
if(new Boolean(false)) - true

**Pull request closed without merging**
