### PR TITLE
Added assertions for NaN

### PR DESCRIPTION
**Pull request by ichernev**
Use
`x.should.be.NaN;`
or
`x.should.not.be.NaN;`

### CODE REVIEW

**Comment by ichernev** [comment]
`isNaN(undefined) === true`, but if you try `undefined.should.be.NaN` it would crash on the `.should` part, so the check is fine the way it is -- you won't get false positives.

**Comment by faridnsh** [comment]
```
isNaN({})
> true
```

`isNaN` will return for everything that is not a number, even if it is an object. I think you should check if it's not equal to itself and it is a number. Also better use `.valueOf` in case if its an object(`new Number(NaN)`).

**Comment by agnoster** [comment]
Looks nice! I was actually just wishing I had this matcher in one of my projects. Hope it gets merged! :+1:

**Comment by agnoster** [comment]
_bump_?

@visionmedia Any concerns or qualms we could address to get this merged?

**Comment by btd** [comment]
In v2

**Pull request closed without merging**
