### PR TITLE
Minor cleanup to `should.exist()`

### PR DESCRIPTION
**Pull request by aseemk**
Improved readme instructions, and moved the tests into the main test suite.

My other pull request for adding custom messages includes these changes, but if you decide not to accept that, you can get this stuff separately.

Cheers,
Aseem

### CODE REVIEW

**Comment by aseemk** [comment]
I added one useful feature here: automatic detection of the common `should.not.exist(err)` use case (e.g. for Node.js-style callbacks). The code now recognizes errors passed in and uses them as the assertion message (instead of "expected {...} not to exist" where {...} is the inspection of the error).

**Comment by tj** [comment]
sounds good, merged

**Comment by aseemk** [comment]
Hmm? Nothing here seems merged; I only see a duplicated commit. =P

(Specifically, the only new commit I see related to this is [a1d5c85](https://github.com/visionmedia/should.js/commit/a1d5c850766a2de6efaa35983fbe836dd0207101) from yesterday, which is identical to commit [0bbf077](https://github.com/visionmedia/should.js/commit/0bbf077a1e295b8479d60c19220902697fbbfe01) from two weeks ago. Nothing from this pull request seems to be merged.)

**Comment by tj** [comment]
hm, maybe your tree is messed up, although git did not bitch at me (that I remember)

**Comment by aseemk** [comment]
I'm only looking here: https://github.com/visionmedia/should.js/commits/master

**Comment by tj** [comment]
yeah, it might not have worked then, your master is probably quite off from mine

**Comment by aseemk** [comment]
My master is indeed quite off, but I was submitting my `feature/exist` branch. =)

**Comment by tj** [comment]
i will have to look into it later

**Comment by c4milo** [comment]
this pull request might solve #25 too

**Comment by jwarchol** [comment]
Hoping to see this get merged in for real soon :+1:

**Pull request closed without merging**
