### PR TITLE
Introduce assertions for each type as in Vows

### PR DESCRIPTION
**Pull request by ForbesLindesay**
Allows you to do things like:

``` javascript
var val = [1,2,3];
val.should.be.an.Array;

val = 10;
val.should.be.a.Number;
```

### CODE REVIEW

**Comment by kilianc** [comment]
+1

**Comment by kilianc** [comment]
Shouldn't it be !== null && all of these ?

``` javascript
console.log({}.constructor === Object);
console.log([].constructor === Array);
console.log((function () {}).constructor === Function);
console.log(''.constructor === String);
console.log(new String().constructor === String); // only for who is wondering if that works
console.log(typeof 454 === 'number');
console.log(true.constructor === Boolean);
```

the API could be something like

``` javascript
val.should.be.a(Constructor);
val.should.be.an(Constructor); // alias
```

managing around the Number exception

``` javascript
if (val === null || val === undefined) {
  // wrong
}
if (constructor === Number) {
  !isNaN(val) && typeof val === 'number';
} else {
   val.constructor === constructor;
}
```

**Comment by stephenmathieson** [comment]
+1

**Comment by btd** [comment]
in v2

**Pull request closed without merging**
