### PR TITLE
Fix 'lengthOf' alias to 'length'

### LINKED ISSUE #167: lengthOf appears broken in 3.0.0
I get a message:
`TypeError: Object #<Assertion> has no method 'lengthOf'`
when calling `.should.have.lengthOf`

looking at the code, it looks the order of arguments to `Assertion.alias`
is reversed.

### PR DESCRIPTION
**Pull request by yamadapc**
I think this fixes the 'lengthOf' alias and thus closes #167.

### CODE REVIEW

**Comment by yamadapc** [comment]
Should I add tests for this?

**Comment by travisjeffery** [comment]
@yamadapc yes please

**Comment by yamadapc** [comment]
There you have it... I tried following the style in https://github.com/visionmedia/should.js/blob/master/test/ext/number.test.js#L84

**Comment by travisjeffery** [comment]
perfect :+1:

**Pull request merged**
