### PR TITLE
Allow for providing arguments directly to throw

### PR DESCRIPTION
**Pull request by skabbes**
This is very helpful for  testing functions which can throw different types of errors, or which should conditionally throw

``` js
var throwsSometimes = function(a){
  if( a === 1 ){
    throw new Error('invalid argument');
  }
};

throwsSometimes.should.throw(1, /^invalid/);
throwsSometimes.should.not.throw(50, /^invalid/);
```

### CODE REVIEW

**Comment by floatingLomas** [comment]
Seriously, this would be good.

I want to do this:

``` javascript
var result = testDevice.create.should.throwError({}, 'Invalid data.');
```

Or this...

``` javascript
var result = testDevice.create.should.throwError('Invalid data.').given({});
```

But my current solution of this...

``` javascript
var error = {};

try {
    var result = testDevice.create({});
} catch(e) {
    error = e;
};

(function () {
    if(error) throw error;
}).should.throwError('Invalid data.');

```

...Looks so yucky.  It works, but ... yucky.

PS: Certainly open to a better way to do it given the current approach, if one exists.

**Comment by tj** [comment]
the anonymous function was just supposed to be a wrapper:

``` js
(function(){
  my.method(to, test, here)
}).should.throw(whatever)
```

**Comment by skabbes** [comment]
this would also work:

``` javascript
my.method.bind(my, to, test, here).should.throw(whatever);
```

or for @floatingLomas 's example

``` javascript
testDevice.create.bind(testDevice, {}).should.throw('Invalid data.');
```

If there's no plan to merge this, let's just close it, ya?

**Comment by floatingLomas** [comment]
Ya, I just realized that the anonymous function makes so much more sense.  It would be nice if that were a bit clearer in the 'throws()' section of the documentation - maybe with an example.  It makes perfect sense now, but it sure didn't at first.

**Pull request closed without merging**
